version: '3'
services:
  dev_db:
    image: mysql:5.7
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root0401
      MYSQL_DATABASE: versioningme_localhost
      MYSQL_USER: two
      MYSQL_PASSWORD: two0401

  test_db:
    image: mysql:5.7
    #    volumes:
    #      - mysql_data:/var/lib/mysql
    #      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root0401
      MYSQL_DATABASE: versioningme_test
      MYSQL_USER: two
      MYSQL_PASSWORD: two0401

#volumes:
#  mysql_data: