#sql-migrate new -config="config/dbconfig.yml" -env="localhost" create_users
#sql-migrate up -config="config/dbconfig.yml" -env="localhost"
vagrant:
  dialect: mysql
  dir: migrations
  datasource: root:root0401@tcp(192.168.33.10:3307)/versioningme_localhost?charset=utf8&collation=utf8_general_ci&parseTime=true

docker:
  dialect: mysql
  dir: migrations
  datasource: two:two0401@tcp(localhost:3307)/versioningme_localhost?charset=utf8&collation=utf8_general_ci&parseTime=true
